### ISSUE TITLE
Customizing FIDO2 registration parameters

### ISSUE THREAD

**Issue by ecmrauh** [loginid1/loginid-tutorial#3]
I followed the instructions and have a working demo app. Everything works as expected, but I would like to customize the FIDO2 registration parameters like attestation type (none, direct), user verification (required, preferred, discourage), resident key [and so on](https://www.w3.org/TR/webauthn-2/#dictionary-makecredentialoptions). Is it possible with this tutorial app and is this supported by LoginID in general?

**Comment by Braagaa** [comment]
@ecmrauh  I'm sorry, but you can't adjust these settings with this product. We are currently working on updating our services to allow you to make these adjustments. I will reach out to you once the updates are available.
